name: add-jira-link-pr-body
on:
  pull_request:
    types: [opened]
    branches: [ main ]

env:
  PR_NUMBER: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.head_ref }}
  BASE_NAME: ${{ github.base_ref }}

jobs:
  add_jira_link:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Jira Link
      run: |
        ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oP 'VREW-\K\d+')
        echo "branch name: ${BRANCH_NAME}"
        echo "base name: ${BASE_NAME}"
        echo "issue number: ${ISSUE_NUMBER}"
        CURRENT_BODY=$(gh pr view $PR_NUMBER --json body -q .body)
        JIRA_LINK="\n## [JIRA ISSUE](https://voyagerx.atlassian.net/browse/VREW-$ISSUE_NUMBER)\n\n---\n"
        NEW_BODY="${JIRA_LINK}${CURRENT_BODY}"
        gh pr edit $PR_NUMBER --body "$NEW_BODY"
        echo "done"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}