name: add-jira-link-pr-body
on:
  pull_request:
    types: [opened]
    branches: [ main ]

jobs:
  add_jira_link:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepend PR Description with Jira Link
      run: |
        BRANCH_NAME=$(echo $GITHUB_HEAD_REF')
        echo $BRANCH_NAME
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}